# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt remove -y nginx
        sudo apt remove -y libgd3
        sudo apt install -y libev-dev libx11-dev libxss-dev libxext-dev libmagickwand-dev libgd-dev
        python -m pip install --upgrade pip
        pip install build cffi
    - name: Build package
      run: |
        export CFLAGS=$(pkg-config --cflags x11 xscrnsaver xext MagickWand gdlib)
        export LDFLAGS=$(pkg-config --libs x11 xscrnsaver xext MagickWand gdlib)
        echo $CFLAGS
        echo $LDFLAGS
        echo $LD_LIBRARY_PATH
        python -m build --no-isolation
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
